### ISSUE TITLE
Create a git tag for the commit that was submitted for eval 3

### ISSUE THREAD

**Issue by bzinberg** [ztangent/Plinf.jl#6]
AFAIK, that is https://github.com/ztangent/Plinf.jl/commit/0cf49ad940e198f70072a198611752a90608218d

**Comment by bzinberg** [comment]
Also, @ztangent, would you be up for transferring this repo to the probcomp organization?

**Comment by ztangent** [comment]
Release is here https://github.com/ztangent/Plinf.jl/releases/tag/v0.1.0

I'm reluctant to transfer this as of yet, because I intend to a substantial rewrite of this at some point soon, and it's as of yet unclear to me which parts should go under `probcomp` vs. the `JuliaPlanners` organization where I've starting moving some of planning code to.

**Comment by bzinberg** [comment]
Thanks!  Could you please add a tag message indicating that this snapshot was used for Eval 3?

```sh
git tag -f v0.1.0 -m "Snapshot used in MCS Eval 3 submission, 2020-12-07"
git push --tags
```
