### ISSUE TITLE
Incorrect Transition in doors-keys-gems

### ISSUE THREAD

**Issue by zcy921716** [ztangent/Plinf.jl#7]
Hi there,
Recently when I played around with your amazing package, I just found there is some issue in the "pickup" action in doors-keys-gems domain. Specifically, the successor state does not delete the (at ?i xpos ypos). I checked the domain file but failed to find any issue. And the transition function works perfectly with the "unlock" action and other actions. Could you take a look what's the issue is?

**Comment by ztangent** [comment]
Thanks for reporting this! I've also been noticing bugs in how the domain was being rendered, and I didn't realize this was due to the transition function. 

Just to check, did you run this with the latest version of PDDL.jl, i.e. PDDL.jl v0.2.0? Because I believe the reason this is happening is because in an earlier version of PDDL.jl, I provided support for a non-standard feature (called [extended unification](https://www.sciencedirect.com/science/article/pii/0743106687900021)) which allowed for numeric fluents like `xpos` to be evaluated in the context of a predicate like `(at ?i ?x ?y)`, but this actually isn't supported in standard PDDL so I've dropped support for it in the updated version of PDDL.jl.

To overcome this issue, I recently re-implemented the doors-keys-gems domain to make use of [array-valued variables](https://github.com/JuliaPlanners/PDDL.jl/blob/master/src/theories/arrays.jl) instead  (see [here](https://github.com/JuliaPlanners/SymbolicPlanners.jl/blob/master/domains/doors-keys-gems/domain.pddl) for the re-implemented version). I just haven't had the chance to update the code in Plinf.jl to use the new domain, but will do so over the next month so. Will update here when that's finished!

**Comment by zcy921716** [comment]
Hi, thank you for your reply.
Yes I run the package with PDDL.jl v0.2.0 and this seems the cause of this issue. Looking forward to your update and just take your time!

________________________________

**Comment by jmchillis** [comment]
Hi, I would also like to thank you for sharing this great package! I have been playing around with it an encountered an issue in the doors-keys-gems example that may be related to this on. I have been able to run the gridworld and blocks world demos but run into trouble with the key and gems examples. The planner returns "nothing" for problems 1-7. I am using the most recent version of PDDL from you repository (PDDL.jl v0.2.4) and Julia 2.6. Do you have any thoughts on why the planner is not working for the keys and gems example but works for others? Thanks!

**Comment by ztangent** [comment]
I unfortunately still have not updated the PDDL domain to work with the newest version of PDDL, but in the meantime, you should be able to run an old version of the demo using [this branch](https://github.com/ztangent/Plinf.jl/tree/neurips-2020-experiments) with PDDL.jl v0.1.x.

**Comment by jmchillis** [comment]
Thank you for the quick response and pointer Zhi-Xuan! I am actually starting to work with Vikash in the capacity of an industry collaboration with Meta Platforms (parent company of Facebook, Instagram, Oculus etc). I will email you shortly to provide a bit more context. In the meantime - thank you!

**Comment by ztangent** [comment]
This issue should finally be addressed as of e7628b5ef!
